//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailProduct
    {
        public int ID { get; set; }
        public Nullable<int> IDSP { get; set; }
        public Nullable<int> IDOP { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<int> IDVoucher { get; set; }
        public string CodeVoucher { get; set; }
    
        public virtual OrderProduct OrderProduct { get; set; }
        public virtual Product Product { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
