//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.DetailProducts = new HashSet<DetailProduct>();
            HinhanhSP = "~/Images/";
        }
    
        public int IDSP { get; set; }
        public string TenSP { get; set; }
        public string MotaSP { get; set; }
        public Nullable<decimal> GiaSP { get; set; }
        public string HinhanhSP { get; set; }
        public Nullable<int> IDVoucher { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailProduct> DetailProducts { get; set; }
        public virtual Voucher Voucher { get; set; }
        public string CodeVoucher { get; internal set; }

        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
    }
}
